### ISSUE TITLE
Platform agnostic dynamic library

### ISSUE THREAD

**Issue by YuanYuYuan** [ZettaScaleLabs/zenoh-flow-examples#4]
During updating the examples, I found that we need to manually change the file extension on different operating systems. For example, `.so` on Linux, `.dylib` on macOS, and `.dll` on Windows. Do you think adding [this](https://docs.rs/libloading/latest/libloading/fn.library_filename.html) to [loader.rs](https://github.com/ZettaScaleLabs/zenoh-flow/blob/master/zenoh-flow/src/runtime/dataflow/loader.rs) would be a good solution? If so, I can try to make a PR for this. Any comments are appreciated.

**Comment by J-Loudet** [comment]
Hi @YuanYuYuan,

We are aware of that limitation (and suffered it as well ;-)) so thanks for the proposal!

We decided to not go in that direction because we are planning to augment Zenoh-Flow with a Registry: a "database" that a Zenoh-Flow daemon is able to query to retrieve nodes. Having this Registry will likely remove the need to specify the path and extension of the libraries (and undoubtedly impact the file `loader.rs`).

**Comment by YuanYuYuan** [comment]
Thanks! I guessed you may already have some cool idea about it. Let me close this issue.
